var annotationArray = [
 {
   "DivID": "a01",
   "Pos": 0.007,
   "SizeW": 100,
   "Text": "The last time we went to the movies together.",
   "Tag1": "grief",
   "Tag2": "connection",
   "Tag3": "",
   "Tag4": "",
   "Tagbreak": 1
 },
 {
   "DivID": "a02",
   "Pos": 0.021,
   "SizeW": 100,
   "Text": "Finding out Dad had cancer.",
   "Tag1": "anguish",
   "Tag2": "numb",
   "Tag3": "",
   "Tag4": "",
   "Tagbreak": 1
 },
 {
   "DivID": "a03",
   "Pos": 0.037,
   "SizeW": 150,
   "Text": "Spending the days hanging out with Dad in the hospital ward, watching movies and reading books.",
   "Tag1": "forbearance",
   "Tag2": "connection",
   "Tag3": "",
   "Tag4": "",
   "Tagbreak": null
 },
 {
   "DivID": "a04",
   "Pos": 0.064,
   "SizeW": 150,
   "Text": "Dad telling me that his cancer was terminal.",
   "Tag1": "anguish",
   "Tag2": "grief",
   "Tag3": "",
   "Tag4": "",
   "Tagbreak": null
 },
 {
   "DivID": "a05",
   "Pos": 0.081,
   "SizeW": 150,
   "Text": "Celebrating my birthday six months early.",
   "Tag1": "joy",
   "Tag2": "grief",
   "Tag3": "",
   "Tag4": "",
   "Tagbreak": null
 },
 {
   "DivID": "a06",
   "Pos": 0.099,
   "SizeW": 200,
   "Text": "Reading to Dad in bed, then kissing him goodnight and saying I'd see him in the morning.",
   "Tag1": "connection",
   "Tag2": "grief",
   "Tag3": "",
   "Tag4": "",
   "Tagbreak": null
 },
 {
   "DivID": "a07",
   "Pos": 0.137,
   "SizeW": 200,
   "Text": "Sitting with Dad early in the morning, after Mum woke me up to tell me he was gone.",
   "Tag1": "connection",
   "Tag2": "grief",
   "Tag3": "",
   "Tag4": "",
   "Tagbreak": null
 },
 {
   "DivID": "a09",
   "Pos": 0.161,
   "SizeW": 175,
   "Text": "Being able to go back to university at the start of semester two.",
   "Tag1": "relief",
   "Tag2": "guilt",
   "Tag3": "",
   "Tag4": "",
   "Tagbreak": null
 },
 {
   "DivID": "a10",
   "Pos": 0.18,
   "SizeW": 150,
   "Text": "Dad's birthday.",
   "Tag1": "grief",
   "Tag2": "anguish",
   "Tag3": "",
   "Tag4": "",
   "Tagbreak": 1
 },
 {
   "DivID": "a11",
   "Pos": 0.214,
   "SizeW": 150,
   "Text": "Getting my memorial tattoos.",
   "Tag1": "grief",
   "Tag2": "connection",
   "Tag3": "numb",
   "Tag4": "",
   "Tagbreak": 1
 },
 {
   "DivID": "a12",
   "Pos": 0.239,
   "SizeW": 200,
   "Text": "Taking a metalworking class, the smell of the studio reminding me of Dad's shed.",
   "Tag1": "grief",
   "Tag2": "longing",
   "Tag3": "",
   "Tag4": "",
   "Tagbreak": null
 },
 {
   "DivID": "a13",
   "Pos": 0.26,
   "SizeW": 200,
   "Text": "Making Dad's chicken soup for my birthday dinner.",
   "Tag1": "connection",
   "Tag2": "longing",
   "Tag3": "",
   "Tag4": "",
   "Tagbreak": null
 },
 {
   "DivID": "a14",
   "Pos": 0.29,
   "SizeW": 200,
   "Text": "Graduating from university in the same week as the second anniversary of Dad's death.",
   "Tag1": "grief",
   "Tag2": "connection",
   "Tag3": "longing",
   "Tag4": "anguish",
   "Tagbreak": 2
 },
 {
   "DivID": "a15",
   "Pos": 0.31,
   "SizeW": 150,
   "Text": "Buying myself welding supplies and steel.",
   "Tag1": "connection",
   "Tag2": "longing",
   "Tag3": "",
   "Tag4": "",
   "Tagbreak": null
 },
 {
   "DivID": "a16",
   "Pos": 0.329,
   "SizeW": 150,
   "Text": "Walking Kokoda with my cousins.",
   "Tag1": "grief",
   "Tag2": "gratitude",
   "Tag3": "",
   "Tag4": "",
   "Tagbreak": null
 },
 {
   "DivID": "a17",
   "Pos": 0.346,
   "SizeW": 200,
   "Text": "Having a dream that Dad was alive, then waking up.",
   "Tag1": "grief",
   "Tag2": "longing",
   "Tag3": "",
   "Tag4": "",
   "Tagbreak": null
 },
 {
   "DivID": "a18",
   "Pos": 0.373,
   "SizeW": 150,
   "Text": "A friend's father passing away.",
   "Tag1": "empathy",
   "Tag2": "grief",
   "Tag3": "",
   "Tag4": "",
   "Tagbreak": null
 },
 {
   "DivID": "a19",
   "Pos": 0.4,
   "SizeW": 200,
   "Text": "Cooking in Dad's favourite cookpot after Mum gave me their Le Creuset.",
   "Tag1": "connection",
   "Tag2": "grief",
   "Tag3": "",
   "Tag4": "",
   "Tagbreak": null
 },
 {
   "DivID": "a20",
   "Pos": 0.448,
   "SizeW": 100,
   "Text": "Impulse buying a camera at the duty free.",
   "Tag1": "connection",
   "Tag2": "longing",
   "Tag3": "",
   "Tag4": "",
   "Tagbreak": 1
 },
 {
   "DivID": "a21",
   "Pos": 0.46,
   "SizeW": 100,
   "Text": "Terry Pratchett dying.",
   "Tag1": "grief",
   "Tag2": "",
   "Tag3": "",
   "Tag4": "",
   "Tagbreak": null
 },
 {
   "DivID": "a22",
   "Pos": 0.482,
   "SizeW": 200,
   "Text": "Crying in the dark at a lecture at the Festival of Dangerous Ideas, wishing he was there listening with me.",
   "Tag1": "longing",
   "Tag2": "grief",
   "Tag3": "",
   "Tag4": "",
   "Tagbreak": null
 },
 {
   "DivID": "a23",
   "Pos": 0.508,
   "SizeW": 80,
   "Text": "Planning my trip to Scotland and Kenya.",
   "Tag1": "longing",
   "Tag2": "connection",
   "Tag3": "",
   "Tag4": "",
   "Tagbreak": 1
 },
 {
   "DivID": "a24",
   "Pos": 0.519,
   "SizeW": 100,
   "Text": "Visiting New Zealand with Mum.",
   "Tag1": "longing",
   "Tag2": "joy",
   "Tag3": "",
   "Tag4": "",
   "Tagbreak": 1
 },
 {
   "DivID": "a25",
   "Pos": 0.531,
   "SizeW": 100,
   "Text": "Seeing a blue whale.",
   "Tag1": "longing",
   "Tag2": "connection",
   "Tag3": "",
   "Tag4": "",
   "Tagbreak": 1
 },
 {
   "DivID": "a26",
   "Pos": 0.547,
   "SizeW": 200,
   "Text": "Spending Dad's birthday in Kenya. Putting my feet on Kenyan soil, sleeping under African stars.",
   "Tag1": "connection",
   "Tag2": "longing",
   "Tag3": "grief",
   "Tag4": "",
   "Tagbreak": 2
 },
 {
   "DivID": "a27",
   "Pos": 0.572,
   "SizeW": 200,
   "Text": "Christmas in the mountains with my family.",
   "Tag1": "connection",
   "Tag2": "joy",
   "Tag3": "grief",
   "Tag4": "",
   "Tagbreak": 2
 },
 {
   "DivID": "a28",
   "Pos": 0.602,
   "SizeW": 150,
   "Text": "My childhood home being sold.",
   "Tag1": "grief",
   "Tag2": "",
   "Tag3": "",
   "Tag4": "",
   "Tagbreak": null
 },
 {
   "DivID": "a29",
   "Pos": 0.628,
   "SizeW": 200,
   "Text": "My wedding day. Wishing my husband could have met my father.",
   "Tag1": "joy",
   "Tag2": "grief",
   "Tag3": "",
   "Tag4": "",
   "Tagbreak": null
 },
 {
   "DivID": "a30",
   "Pos": 0.649,
   "SizeW": 150,
   "Text": "Going back to university to study data science.",
   "Tag1": "longing",
   "Tag2": "connection",
   "Tag3": "grief",
   "Tag4": "",
   "Tagbreak": 2
 },
 {
   "DivID": "a31",
   "Pos": 0.669,
   "SizeW": 225,
   "Text": "Family Christmas at Nambucca. Hugging Mum while we walked on the beach, remembering so much time spent there together.",
   "Tag1": "joy",
   "Tag2": "grief",
   "Tag3": "longing",
   "Tag4": "",
   "Tagbreak": null
 },
 {
   "DivID": "a32",
   "Pos": 0.701,
   "SizeW": 150,
   "Text": "Breadbox question vindication.",
   "Tag1": "connection",
   "Tag2": "grief",
   "Tag3": "longing",
   "Tag4": "",
   "Tagbreak": 2
 },
 {
   "DivID": "a33",
   "Pos": 0.73,
   "SizeW": 150,
   "Text": "My husband finding a (benign) lump on his neck.",
   "Tag1": "healthanxiety",
   "Tag2": "anguish",
   "Tag3": "",
   "Tag4": "",
   "Tagbreak": 1
 },
 {
   "DivID": "a34",
   "Pos": 0.762,
   "SizeW": 200,
   "Text": "Rereading <i>The Hogfather</i> at Christmastime, the first Pratchett book Dad bought me.",
   "Tag1": "connection",
   "Tag2": "",
   "Tag3": "",
   "Tag4": "",
   "Tagbreak": null
 },
 {
   "DivID": "a35",
   "Pos": 0.788,
   "SizeW": 150,
   "Text": "Suggestion that we scatter Dad's ashes.",
   "Tag1": "familyconflict",
   "Tag2": "longing",
   "Tag3": "",
   "Tag4": "",
   "Tagbreak": 1
 },
 {
   "DivID": "a36",
   "Pos": 0.803,
   "SizeW": 150,
   "Text": "Driving our dog to and from the vet when they were very ill.",
   "Tag1": "forbearance",
   "Tag2": "numb",
   "Tag3": "",
   "Tag4": "",
   "Tagbreak": null
 },
 {
   "DivID": "a37",
   "Pos": 0.82,
   "SizeW": 225,
   "Text": "Spending time at vet hospital with a very sick dog. The feeling of desperately wanting something to be different but not being able to change it.",
   "Tag1": "anguish",
   "Tag2": "",
   "Tag3": "",
   "Tag4": "",
   "Tagbreak": null
 },
 {
   "DivID": "a38",
   "Pos": 0.845,
   "SizeW": 100,
   "Text": "Starting to think about this project.",
   "Tag1": "grief",
   "Tag2": "",
   "Tag3": "",
   "Tag4": "",
   "Tagbreak": null
 },
 {
   "DivID": "a39",
   "Pos": 0.86,
   "SizeW": 200,
   "Text": "Telling my Mum I was pregnant, then going for a swim in the ocean to tell Dad too.",
   "Tag1": "joy",
   "Tag2": "longing",
   "Tag3": "",
   "Tag4": "",
   "Tagbreak": null
 },
 {
   "DivID": "a40",
   "Pos": 0.88,
   "SizeW": 100,
   "Text": "Our dog dying.",
   "Tag1": "anguish",
   "Tag2": "",
   "Tag3": "",
   "Tag4": "",
   "Tagbreak": null
 },
 {
   "DivID": "a41",
   "Pos": 0.898,
   "SizeW": 150,
   "Text": "Thinking about lost loved ones being characters in our baby's life, instead of presences.",
   "Tag1": "grief",
   "Tag2": "",
   "Tag3": "",
   "Tag4": "",
   "Tagbreak": null
 },
 {
   "DivID": "a42",
   "Pos": 0.912,
   "SizeW": 150,
   "Text": "My husband photographing our newborn daughter with my Dad's camera.",
   "Tag1": "connection",
   "Tag2": "longing",
   "Tag3": "",
   "Tag4": "",
   "Tagbreak": 1
 },
 {
   "DivID": "a43",
   "Pos": 0.932,
   "SizeW": 200,
   "Text": "Christmas stockings with oranges in them. Missing the magic of having someone else make my stocking.",
   "Tag1": "connection",
   "Tag2": "longing",
   "Tag3": "grief",
   "Tag4": "",
   "Tagbreak": 2
 },
 {
   "DivID": "a44",
   "Pos": 0.953,
   "SizeW": 150,
   "Text": "Taking my baby to see the pacific ocean to say hi to Grandpa.",
   "Tag1": "connection",
   "Tag2": "longing",
   "Tag3": "",
   "Tag4": "",
   "Tagbreak": 1
 },
 {
   "DivID": "a45",
   "Pos": 0.967,
   "SizeW": 150,
   "Text": "Making the dataset for this project.",
   "Tag1": "grief",
   "Tag2": "longing",
   "Tag3": "connection",
   "Tag4": "anguish",
   "Tagbreak": 2
 },
 {
   "DivID": "a46",
   "Pos": 0.986,
   "SizeW": 100,
   "Text": "Crocheting the last row of the dataset.",
   "Tag1": "grief",
   "Tag2": "",
   "Tag3": "",
   "Tag4": "",
   "Tagbreak": null
 }
]